services:
  mysql:
    image: mysql:8.0
    container_name: myracing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: myracing
      MYSQL_USER: admin
      MYSQL_PASSWORD: MiR@cing_2025!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myracing-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-pMiR@cing_2025!"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  myracing-network:
    driver: bridge
